name: photoqt
base: core18
version: '2.4'
summary: Fast and highly configurable image viewer
description: |
    Fast and highly configurable image viewer with a simple and nice interface, supporting well over 100 image formats.

grade: stable
confinement: strict

parts:
    exiv275:
        build-snaps:
            - cmake
        source: https://exiv2.org/builds/exiv2-0.27.5-Source.tar.gz
        plugin: cmake
    photoqt:
        after:
            - exiv275
            - desktop-qt5
        source: https://photoqt.org/downloads/source/photoqt-2.4.snap.tar.gz
        plugin: cmake
        configflags:
            - "-DPOPPLER=OFF"
            - "-DGRAPHICSMAGICK=ON"
            - "-DIMAGEMAGICK=OFF"
            - "-DLibExiv2_INCLUDE_DIRS=$SNAPCRAFT_STAGE/include"
            - "-DLibExiv2_LIBRARIES=$SNAPCRAFT_STAGE/lib"
        build-snaps:
            - cmake
            - kde-frameworks-5-core18-sdk
        build-packages:
            - libegl1-mesa-dev
            - libarchive-dev
            - libdevil-dev
            - libfreeimageplus-dev
            - libraw-dev
            - libgraphicsmagick++1-dev
            - libpugixml-dev
            - libexpat1-dev
            - qtdeclarative5-dev
            - libqt5svg5-dev
            - qtmultimedia5-dev
            - qttools5-dev
            - extra-cmake-modules
        stage-packages:
            - libgraphicsmagick++-q16-12
            - libraw16
            - libfreeimageplus3
            - libdevil1c2
            - libarchive13
            - libpugixml1v5
            - libslang2
            - freeglut3
            - libxcomposite1
            - libxinerama1
            - libxrandr2
            - libatk1.0-0
            - libgtk2.0-0
            - libqt5qml5
            - libqt5quick5
            - libqt5sql5
            - libqt5sql5-sqlite
            - qml-module-qtquick2
            - qml-module-qtquick-window2
            - qml-module-qtquick-layouts
            - qml-module-qtquick-controls2
            - qml-module-qtquick-controls
            - qml-module-qt-labs-platform
            - qml-module-qtquick-dialogs
            - qml-module-qtmultimedia
            - libqt5multimedia5
            - libqt5multimedia5-plugins
            - qtwayland5
            
slots:
    dbus-slot:
        interface: dbus
        bus: session
        name: org.photoqt.PhotoQt

plugs:
    dbus-plug:
        interface: dbus
        bus: session
        name: org.photoqt.PhotoQt

apps:
    photoqt:
        command: desktop-launch photoqt
        plugs:
            - x11
            - wayland
            - opengl
            - desktop
            - audio-playback
            - home
            - network
        slots:
            - dbus-slot
        plugs:
            - dbus-plug
